dataset: partnet
root: data/partnet/fpfh_rigid
descriptor: fpfh
inlier_threshold: 0.10
downsample: 0.02
re_thre: 15
te_thre: 30
val_ratio: 0.1
use_features: true
feature_dim: 33
neg_ratio: 2.0
full_data: false
max_corr: -1
seed_ratio: 0.2
num_node: 512
batch_size: 16
num_workers: 12
skip_gt_trans: true
max_epoch: 100

dropout: 0.5
All_num_layers: 6
MLP_num_layers: 1
MLP_hidden: 64
Classifier_num_layers: 1
Classifier_hidden: 128
aggregate: mean
normalization: ln
restart_alpha: 0.5
proc_type: MLP
pooling_type: FPSWE
apprepset_n_anchors: 128
isab_num_inds: 32
